dist: bionic
language: python

jobs:
  include:
  - stage: test
    env: PYTHON3
    python: 3.6
    install:
     - pip -q install -U flake8
    script:
     - flake8 ./python/
  - stage: test
    env: POSTGRES
    addons:
      postgresql: 11
      apt:
        packages:
        - postgresql-11-postgis-2.5
        - postgresql-11
        - postgresql-11-client
	env:
	  global:
	  - PGPORT=5433

    before_script:
     - echo "\set ON_ERROR_STOP on" > ~/.psqlrc
     - sudo pg_ctlcluster 11 main start
     - sudo pg_ctlcluster 11 main status
     - sudo cat /etc/postgresql/11/main/postgresql.conf
     - sudo echo "host    all             all             127.0.0.1/32            md5" >> /etc/postgresql/11/main/pg_hba.conf
     - sudo cat /etc/postgresql/11/main/pg_hba.conf
     - sudo cat /etc/postgresql/9.3/main/postgresql.conf
     - sudo cat /etc/postgresql/9.3/main/pg_hba.conf
     - export PATH="/usr/lib/postgresql/11/bin:$PATH"
     - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
    script:
     - id
     - cd sql; 
     - sed -e 's/@DB_USER@/postgres/' db_settings.sh.template > db_settings.sh; 
     - cat db_settings.sh
     - createdb -w -p 5433 -h localhost cf
     - psql -w  -p 5433  -h localhost cf -e "create extension postgis"
     - psql -w  -p 5433  -h localhost cf -f create-users.sql
     - psql -w  -p 5433  -h localhost cf -f 00-common-schema.sql
     - psql -w  -p 5433  -h localhost cf -f 01-taxonomy2human.sql
     - psql -w  -p 5433  -h localhost cf -f 02-hazard-schema.sql
     - psql -w  -p 5433  -h localhost cf -f 03-ged4all-schema.sql
     - psql -w  -p 5433  -h localhost cf -f 04-loss-schema.sql
     - psql -w  -p 5433  -h localhost cf -f 05-mover-schema.sql
     - psql -w  -p 5433  -h localhost cf -f 06-permisions.sql
