# Welcome to Serverless!

service: api

provider:
  name: aws
  runtime: python3.7

functions:
  GraphQL:
    handler: common/lambda.handler
    events:
    - http:
        path: /test
        method: get
  healthCheck:
    handler: handlers/app.lambda_handler
    events:
    - http:
        path: /health
        method: get

plugins:
  - serverless-offline

